// Mocks generated by Mockito 5.4.6 from annotations
// in aerial_views/test/immich_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aerial_views/src/models/immich_models.dart' as _i2;
import 'package:aerial_views/src/providers/immich_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedLinkResponse_0 extends _i1.SmartFake
    implements _i2.SharedLinkResponse {
  _FakeSharedLinkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImmichAlbum_1 extends _i1.SmartFake implements _i2.ImmichAlbum {
  _FakeImmichAlbum_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchAssetsResponse_2 extends _i1.SmartFake
    implements _i2.SearchAssetsResponse {
  _FakeSearchAssetsResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImmichApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockImmichApi extends _i1.Mock implements _i3.ImmichApi {
  MockImmichApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serverUrl =>
      (super.noSuchMethod(
            Invocation.getter(#serverUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serverUrl),
            ),
          )
          as String);

  @override
  void setPrefs(_i2.ImmichMediaPrefs? prefs) => super.noSuchMethod(
    Invocation.method(#setPrefs, [prefs]),
    returnValueForMissingStub: null,
  );

  @override
  void setResolvedSharedKey(String? key) => super.noSuchMethod(
    Invocation.method(#setResolvedSharedKey, [key]),
    returnValueForMissingStub: null,
  );

  @override
  String getAssetUri(String? id, bool? isVideo) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetUri, [id, isVideo]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getAssetUri, [id, isVideo]),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.SharedLinkResponse> getSharedAlbum({
    String? key,
    String? slug,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedAlbum, [], {
              #key: key,
              #slug: slug,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.SharedLinkResponse>.value(
              _FakeSharedLinkResponse_0(
                this,
                Invocation.method(#getSharedAlbum, [], {
                  #key: key,
                  #slug: slug,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.SharedLinkResponse>);

  @override
  _i5.Future<List<_i2.ImmichAlbum>> getAlbums({bool? shared}) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbums, [], {#shared: shared}),
            returnValue: _i5.Future<List<_i2.ImmichAlbum>>.value(
              <_i2.ImmichAlbum>[],
            ),
          )
          as _i5.Future<List<_i2.ImmichAlbum>>);

  @override
  _i5.Future<_i2.ImmichAlbum> getAlbum(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [albumId]),
            returnValue: _i5.Future<_i2.ImmichAlbum>.value(
              _FakeImmichAlbum_1(this, Invocation.method(#getAlbum, [albumId])),
            ),
          )
          as _i5.Future<_i2.ImmichAlbum>);

  @override
  _i5.Future<_i2.ImmichAlbum> getSharedAlbumById(
    String? albumId, {
    required String? key,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSharedAlbumById,
              [albumId],
              {#key: key, #password: password},
            ),
            returnValue: _i5.Future<_i2.ImmichAlbum>.value(
              _FakeImmichAlbum_1(
                this,
                Invocation.method(
                  #getSharedAlbumById,
                  [albumId],
                  {#key: key, #password: password},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ImmichAlbum>);

  @override
  _i5.Future<_i2.SearchAssetsResponse> searchAssets(
    _i2.SearchMetadataRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchAssets, [request]),
            returnValue: _i5.Future<_i2.SearchAssetsResponse>.value(
              _FakeSearchAssetsResponse_2(
                this,
                Invocation.method(#searchAssets, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.SearchAssetsResponse>);

  @override
  _i5.Future<List<_i2.ImmichAsset>> getRandomAssets(
    _i2.SearchMetadataRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomAssets, [request]),
            returnValue: _i5.Future<List<_i2.ImmichAsset>>.value(
              <_i2.ImmichAsset>[],
            ),
          )
          as _i5.Future<List<_i2.ImmichAsset>>);
}
